# -*- coding: utf-8 -*-
"""Project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tlq2Ar4vgzeuGP74TO94Oy0pSfypb6Ma
"""

import pandas as pd
import numpy as np

# 1. Dataset Load karna
df = pd.read_csv("European_Bank.csv")

# 2. Non-analytical field hatana (Surname hatayenge, CustomerId rakhenge validation ke liye)
df.drop(['Surname'], axis=1, inplace=True)

# 3. Age Segmentation (As per Requirements: <30, 30–45, 46–60, 60+)
df['AgeGroup'] = pd.cut(
    df['Age'],
    bins=[0, 30, 45, 60, 120],
    labels=['<30', '30-45', '46-60', '60+'],
    right=True
)

# 4. Tenure Grouping (Corrected Boundaries: New, Mid-term, Long-term)
df['TenureGroup'] = pd.cut(
    df['Tenure'],
    bins=[-1, 2, 7, 11],
    labels=['New', 'Mid-term', 'Long-term'],
    right=True
)

# 5. Credit Score Bands
df['CreditBand'] = pd.cut(
    df['CreditScore'],
    bins=[0, 580, 700, 850],
    labels=['Low', 'Medium', 'High'],
    right=True
)

# 6. Balance Segmentation (Isolating Zero-Balance explicitly)
def segment_balance(val):
    if val == 0:
        return 'Zero Balance'
    elif val <= 100000:
        return 'Low Balance'
    else:
        return 'High Balance'

df['BalanceSegment'] = df['Balance'].apply(segment_balance)

# 7. High-Value Customer Definition (Top 25% Balance OR Top 25% Salary)
balance_q75 = df['Balance'].quantile(0.75)
salary_q75 = df['EstimatedSalary'].quantile(0.75)

df['HighValueFlag'] = np.where(
    (df['Balance'] >= balance_q75) | (df['EstimatedSalary'] >= salary_q75),
    'High-Value',
    'Standard'
)

# 8. Activity Status String Format me (Tableau me easily user filter use kar sakega)
df['ActivityStatus'] = np.where(df['IsActiveMember'] == 1, 'Active', 'Inactive')

# 9. Verify karne ke liye prints
print("Data fully processed!")
print(df['HighValueFlag'].value_counts())

# 10. File ko export aur download karna Tableau ke liye
df.to_csv("European_Bank_Tableau_Ready.csv", index=False)

from google.colab import files
files.download("European_Bank_Tableau_Ready.csv")